//LOCAL HOST
// GET ALL
GET https://codenamesdb.onrender.com
###
// GET CODE
GET https://codenamesdb.onrender.com
###
// GET ALL CODES
GET https://codenamesdb.onrender.com/getAllCodes
###
// CREATE NEW
POST https://codenamesdb.onrender.com/createFromWords HTTP/1.1 
content-type: application/json

{
    "type": "Base",
    "wordList": [
        "AFRICA",
        "AGENT",
        "AIR",
        "ALIEN",
        "ALPS",
        "AMAZON",
        "AMBULANCE",
        "AMERICA",
        "ANGEL",
        "ANTARCTICA",
        "APPLE",
        "ARM",
        "ATLANTIS",
        "AUSTRALIA",
        "AZTEC",
        "BACK",
        "BALL",
        "BAND",
        "BANK",
        "BAR",
        "BARK",
        "BAT",
        "BATTERY",
        "BEACH",
        "BEAR",
        "BEAT",
        "BED",
        "BEIJING",
        "BELL",
        "BELT",
        "BERLIN",
        "BERMUDA",
        "BERRY",
        "BILL",
        "BLOCK",
        "BOARD",
        "BOLT",
        "BOMB",
        "BOND",
        "BOOM",
        "BOOT",
        "BOTTLE",
        "BOW",
        "BOX",
        "BRIDGE",
        "BRUSH",
        "BUCK",
        "BUFFALO"
    ]
}


